# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/agent_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "protos/agent_service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1aprotos/agent_service.proto\x12\x0c\x61gentservice"\x1c\n\x0c\x41gentRequest\x12\x0c\n\x04task\x18\x01 \x01(\t"b\n\rAgentResponse\x12\x12\n\nagent_type\x18\x01 \x01(\t\x12\x0c\n\x04task\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t2\xac\x01\n\x0c\x41gentService\x12O\n\x14\x45xecuteLangraphAgent\x12\x1a.agentservice.AgentRequest\x1a\x1b.agentservice.AgentResponse\x12K\n\x10\x45xecuteLyzrAgent\x12\x1a.agentservice.AgentRequest\x1a\x1b.agentservice.AgentResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "protos.agent_service_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_AGENTREQUEST"]._serialized_start = 44
    _globals["_AGENTREQUEST"]._serialized_end = 72
    _globals["_AGENTRESPONSE"]._serialized_start = 74
    _globals["_AGENTRESPONSE"]._serialized_end = 172
    _globals["_AGENTSERVICE"]._serialized_start = 175
    _globals["_AGENTSERVICE"]._serialized_end = 347
# @@protoc_insertion_point(module_scope)
