# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from dummy_agents.protos import agent_service_pb2 as protos_dot_agent__service__pb2

GRPC_GENERATED_VERSION = "1.75.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in protos/agent_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class AgentServiceStub:
    """Agent service definition"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteLangraphAgent = channel.unary_unary(
            "/agentservice.AgentService/ExecuteLangraphAgent",
            request_serializer=protos_dot_agent__service__pb2.AgentRequest.SerializeToString,
            response_deserializer=protos_dot_agent__service__pb2.AgentResponse.FromString,
            _registered_method=True,
        )
        self.ExecuteLyzrAgent = channel.unary_unary(
            "/agentservice.AgentService/ExecuteLyzrAgent",
            request_serializer=protos_dot_agent__service__pb2.AgentRequest.SerializeToString,
            response_deserializer=protos_dot_agent__service__pb2.AgentResponse.FromString,
            _registered_method=True,
        )


class AgentServiceServicer:
    """Agent service definition"""

    def ExecuteLangraphAgent(self, request, context):
        """Execute Langraph agent (gRPC endpoint 1)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExecuteLyzrAgent(self, request, context):
        """Execute Lyzr agent (gRPC endpoint 2)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ExecuteLangraphAgent": grpc.unary_unary_rpc_method_handler(
            servicer.ExecuteLangraphAgent,
            request_deserializer=protos_dot_agent__service__pb2.AgentRequest.FromString,
            response_serializer=protos_dot_agent__service__pb2.AgentResponse.SerializeToString,
        ),
        "ExecuteLyzrAgent": grpc.unary_unary_rpc_method_handler(
            servicer.ExecuteLyzrAgent,
            request_deserializer=protos_dot_agent__service__pb2.AgentRequest.FromString,
            response_serializer=protos_dot_agent__service__pb2.AgentResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "agentservice.AgentService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "agentservice.AgentService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class AgentService:
    """Agent service definition"""

    @staticmethod
    def ExecuteLangraphAgent(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/agentservice.AgentService/ExecuteLangraphAgent",
            protos_dot_agent__service__pb2.AgentRequest.SerializeToString,
            protos_dot_agent__service__pb2.AgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ExecuteLyzrAgent(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/agentservice.AgentService/ExecuteLyzrAgent",
            protos_dot_agent__service__pb2.AgentRequest.SerializeToString,
            protos_dot_agent__service__pb2.AgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
